In [31]:
import pandas as pd
import pickle as pkl

In [75]:
standings_pkl = pkl.load(open('data/standings_df.pkl', 'rb'))

In [60]:
standings_pkl.head(4)

,team_id,team_key,name,url,manager_id,manager_nickname,is_comanager,is_commissioner,manager_image_url,felo_score,...,number_of_moves,number_of_trades,team_paid,waiver_priority,team_logo,roster_adds,division_id,faab_balance,previous_season_team_rank,win_probability
0,2,199.l.407818.t.2,b'LaserFloyd',https://football.fantasysports.yahoo.com/2008/...,2,Zoysia88,0,0,https://s.yimg.com/ag/images/4570/38823577682_...,None,...,3,0,0,None,,0,,,,
1,6,199.l.407818.t.6,b'touchdownz',https://football.fantasysports.yahoo.com/2008/...,6,kevin mc,0,0,https://s.yimg.com/ag/images/default_user_prof...,None,...,9,0,0,None,,0,,,,
2,3,199.l.407818.t.3,b'Old Gregg',https://football.fantasysports.yahoo.com/2008/...,3,Jacob,0,0,https://s.yimg.com/ag/images/default_user_prof...,None,...,17,0,0,None,,0,,,,
3,8,199.l.407818.t.8,b'stoop kid',https://football.fantasysports.yahoo.com/2008/...,8,--hidden--,0,0,,None,...,11,0,0,None,,0,,,,

In [76]:
draft_results = pkl.load(open('data/draft_results_df.pkl', 'rb'))

In [79]:
draft_results.head(5)

,season,team_id,round,pick,cost,player_key,player_name,player_position
0,2008,199.l.407818.t.2,1,4,None,199.p.5228,,
1,2008,199.l.407818.t.2,2,17,None,199.p.7179,,
2,2008,199.l.407818.t.2,3,24,None,199.p.100016,,
3,2008,199.l.407818.t.2,4,37,None,199.p.5854,,
4,2008,199.l.407818.t.2,5,44,None,199.p.6913,,

In [54]:
draft_results['player_key'].value_counts()

player_key
199.p.5228      1
199.p.7179      1
199.p.100016    1
199.p.5854      1
199.p.6913      1
               ..
406.p.30118     1
406.p.24017     1
406.p.25876     1
406.p.32682     1
406.p.100005    1
Name: count, Length: 2170, dtype: int64

In [80]:
matchups = pkl.load(open('data/matchups_df.pkl', 'rb'))
matchups.head(3)

,season,team_id,week,week_start,week_end,status,is_playoffs,is_consolation,is_tied,opponent_team_key,opponent_team_name,our_points,opponent_points,winner_team_key
0,2008,199.l.407818.t.2,1,2008-09-02,2008-09-08,postevent,0,0,0,199.l.407818.t.1,b'Bring Back Barry',118.8,117.5,199.l.407818.t.2
1,2008,199.l.407818.t.2,2,2008-09-09,2008-09-15,postevent,0,0,0,199.l.407818.t.10,b'Ringer4heisman',66.2,97.05,199.l.407818.t.10
2,2008,199.l.407818.t.2,3,2008-09-16,2008-09-22,postevent,0,0,0,199.l.407818.t.3,b'Old Gregg',96.9,141.85,199.l.407818.t.3

In [81]:
rosters = pkl.load(open('data/rosters_df.pkl', 'rb'))
rosters.head()

,season,team_id,coverage_type,week,player_key,player_id,name,position,eligible_positions,player_points,player_projected_points,status,status_last_updated,bye_weeks,injury_note,nfl_team_id
0,2008,199.l.407818.t.2,,16,199.p.7200,7200,Aaron Rodgers,,QB,,,,,0,,
1,2008,199.l.407818.t.2,,16,199.p.7179,7179,Braylon Edwards,,WR,,,,,0,,
2,2008,199.l.407818.t.2,,16,199.p.3514,3514,Marvin Harrison,,WR,,,,,0,,
3,2008,199.l.407818.t.2,,16,199.p.7776,7776,DeAngelo Williams,,RB,,,,,0,,
4,2008,199.l.407818.t.2,,16,199.p.5036,5036,Thomas Jones,,RB,,,,,0,,

In [74]:
rosters[rosters['player_id'] == '7200']['name'][0]

'Name({\n  "ascii_first": "Aaron",\n  "ascii_last": "Rodgers",\n  "first": "Aaron",\n  "full": "Aaron Rodgers",\n  "last": "Rodgers"\n})'

In [32]:
rosters = pkl.load(open('data/rosters_df.pkl', 'rb'))

In [33]:
rosters

,season,team_id,coverage_type,week,player_key,player_id,name,position,eligible_positions,player_points,player_projected_points,status,status_last_updated,bye_weeks,injury_note,nfl_team_id
0,2008,199.l.407818.t.2,,16,199.p.7200,7200,"Name({\n ""ascii_first"": ""Aaron"",\n ""ascii_la...",,QB,,,,,0,,
1,2008,199.l.407818.t.2,,16,199.p.7179,7179,"Name({\n ""ascii_first"": ""Braylon"",\n ""ascii_...",,WR,,,,,0,,
2,2008,199.l.407818.t.2,,16,199.p.3514,3514,"Name({\n ""ascii_first"": ""Marvin"",\n ""ascii_l...",,WR,,,,,0,,
3,2008,199.l.407818.t.2,,16,199.p.7776,7776,"Name({\n ""ascii_first"": ""DeAngelo"",\n ""ascii...",,RB,,,,,0,,
4,2008,199.l.407818.t.2,,16,199.p.5036,5036,"Name({\n ""ascii_first"": ""Thomas"",\n ""ascii_l...",,RB,,,,,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2201,2021,406.l.197495.t.4,,17,406.p.33398,33398,"Name({\n ""ascii_first"": ""DeVonta"",\n ""ascii_...",,WR,,,,,14,,
2202,2021,406.l.197495.t.4,,17,406.p.33408,33408,"Name({\n ""ascii_first"": ""Kadarius"",\n ""ascii...",,WR,,,NA,,13,Shoulder,
2203,2021,406.l.197495.t.4,,17,406.p.31883,31883,"Name({\n ""ascii_first"": ""A.J."",\n ""ascii_las...",,WR,,,,,14,,
2204,2021,406.l.197495.t.4,,17,406.p.31906,31906,"Name({\n ""ascii_first"": ""Devin"",\n ""ascii_la...",,RB,,,,,10,,
2205,2021,406.l.197495.t.4,,17,406.p.100026,100026,"Name({\n ""ascii_first"": ""Seahawks"",\n ""ascii...",,DEF,,,,,9,,